#!/bin/bash

VERSION="1.0.0"
NAME="next-cloud-link-tracker"
FULL_NAME="${NAME}:${VERSION}"
LAST_NAME="${NAME}:last"
PLATFORMS="linux/amd64"
#PLATFORMS="linux/arm/v7,linux/amd64"

mkdir -p out

podman build --format docker --platform ${PLATFORMS} -t "${FULL_NAME}" -f build/Dockerfile .
podman tag "${FULL_NAME}" "${LAST_NAME}"

rm "./out/${NAME}_${VERSION}.img"
podman save -o "./out/${NAME}_${VERSION}.img" "${FULL_NAME}"
